#include "../../includes/webserv.hpp"

/*
Résumé des fonctions finales

    Sockets : socket, bind, listen, accept.
    Événements : epoll_create, epoll_ctl, epoll_wait (ou poll).
    Communication : send, recv.
    DNS : getaddrinfo, freeaddrinfo.
    Processus : fork, signal, kill.
    Fichiers : close, fcntl.
*/

void ft_bomb_as_been_defused(char *msg)
{
	perror(msg);
	exit(errno);
}

char *ft_call_cgi(char *ans)
{
	int fds[2];
    const char	*python_path = "/usr/bin/python3";
    const char	*script_path = "../../CGI.py";
    char *const argv[] = { "python3", (char *)script_path, NULL }; // Format for execve

	pipe(fds);
    if (fork() == 0)
	{
		close(fds[0]);
		dup2(fds[1], STDOUT_FILENO);
		if (execve(python_path, argv, 0) == -1)
		{
        	perror("Erreur lors de l'exécution de execve");
        	exit(EXIT_FAILURE);
		}
    }
	close(fds[1]);
	wait(&fds[1]);
	read(fds[0], ans, 3);
	close(fds[0]);
    return (ans);
}

void	ft_setup_socket(int *server_fd)
{
	struct sockaddr_in	addr_serv;

	*server_fd = socket(AF_INET, SOCK_STREAM, 0);	// socket creation as ipv4
	memset(&addr_serv, 0, sizeof(addr_serv));		// switch any bytes to 0
	addr_serv.sin_family = AF_INET;					// server will use ipv4
	addr_serv.sin_port = htons(8080);				
	inet_pton(AF_INET, "127.0.0.1", &addr_serv.sin_addr); // server will listen 127.0.0.1:8080

	if (bind(*server_fd, (const struct sockaddr *)&addr_serv, sizeof(addr_serv)) == -1) // link socket the addr:port
		ft_bomb_as_been_defused("BIND ERROR\n");
	if (listen(*server_fd, 5) < 0) 														//lock socket in listen mode
		ft_bomb_as_been_defused("LISTEN ERROR\n");
	printf("SERVER IS ONLINE\n");
}

void	ft_deverse_html(const char *htmp_file)
{
	
}

void ft_comm(void) // execute socket
{
	struct sockaddr		addr_client;
	socklen_t			addr_len;
    int					server_fd;
	int					client_fd;
    unsigned char		buffer[1024] = {0};
	int					fd_page;
	unsigned char 		buffer_page[8192] = {0};
	char				str[5] = {0};

	addr_len = sizeof(struct sockaddr_in);
	ft_setup_socket(&server_fd);
    while (1)
	{
        while ((client_fd = accept(server_fd, &addr_client, &addr_len)) == -1)
		{
            if (errno != EINTR)
				continue; 
            ft_bomb_as_been_defused("ACCEPT ERROR\n");
        }
		recv(client_fd, &buffer, 1024, 0); //Read and put in buffer http request
		if (!strncmp("GET /random", buffer, 10)) //if http request want to use CGI (random)
			send(client_fd, ft_call_cgi(str), 3, 0); // send the number generated by ft_call_cgi
		else 
		{		//send the default htmp page
			fd_page = open("../../html/index.html", O_RDONLY, 0666);
			read(fd_page, buffer_page, 1501);
			send(client_fd, buffer_page, strlen(buffer_page), 0); //use what has beed received as an answer 
			write(1, buffer, strlen(buffer)); // print all received message in terminal
			close(client_fd);
			close(fd_page);
		}
		memset(&buffer, 0, 1024);
		close(client_fd);
	}
}

int main(void)
{
	ft_comm();
}
